-- Esquema inicial de FinScope.
--
-- Reproduce el estado con el que la aplicacion ya venia funcionando, para que una base de
-- datos vacia quede exactamente igual que la que se creo a mano durante el desarrollo. En
-- las bases que ya existen esta migracion no se ejecuta: `baseline-on-migrate` las marca en
-- la version 1 y solo aplica lo que venga despues.

CREATE TABLE users (
    id_user       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email         varchar(255) NOT NULL,
    password_hash varchar(100),
    display_name  varchar(70),
    active        boolean      NOT NULL DEFAULT true,
    created_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- El correo identifica la cuenta sin distinguir mayusculas, asi que la unicidad se declara
-- sobre su version en minusculas: es lo que consulta el inicio de sesion.
CREATE UNIQUE INDEX uq_users_email ON users (lower(email));

CREATE TABLE user_identities (
    id_identity bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     bigint      NOT NULL REFERENCES users (id_user) ON DELETE CASCADE,
    provider    varchar(30) NOT NULL,
    subject     varchar(255) NOT NULL,
    CONSTRAINT uq_user_identities_provider_subject UNIQUE (provider, subject)
);

CREATE INDEX idx_user_identities_user_id ON user_identities (user_id);

CREATE TABLE refresh_tokens (
    id_refresh_token bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id          bigint      NOT NULL REFERENCES users (id_user) ON DELETE CASCADE,
    token_hash       varchar(64) NOT NULL,
    expires_at       timestamp   NOT NULL,
    revoked          boolean     NOT NULL DEFAULT false,
    created_at       timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE transaction_types (
    id_transaction_type   integer      NOT NULL PRIMARY KEY,
    name_transaction_type varchar(70)  NOT NULL,
    code                  varchar(20)  NOT NULL,
    CONSTRAINT chk_transaction_types_code CHECK (code IN ('INCOME', 'EXPENSE'))
);

CREATE UNIQUE INDEX uq_transaction_types_code ON transaction_types (code);

-- Catalogo fijo del dominio, no dato de usuario: los identificadores se fijan aqui porque
-- las transacciones los referencian y deben valer lo mismo en cualquier entorno.
INSERT INTO transaction_types (id_transaction_type, name_transaction_type, code) VALUES
    (1, 'Ingreso', 'INCOME'),
    (2, 'Egreso', 'EXPENSE');

CREATE TABLE categories (
    id_category   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id       bigint      NOT NULL REFERENCES users (id_user) ON DELETE CASCADE,
    name_category varchar(70) NOT NULL,
    applies_to    varchar(10) NOT NULL DEFAULT 'EXPENSE',
    is_system     boolean     NOT NULL DEFAULT false,
    CONSTRAINT chk_categories_applies_to CHECK (applies_to IN ('EXPENSE', 'INCOME', 'BOTH'))
);

CREATE UNIQUE INDEX uq_categories_user_name ON categories (user_id, lower(name_category));

-- Cada usuario tiene como mucho una categoria de sistema: es la que recoge las
-- transacciones de las categorias que borre, y no tendria sentido que hubiera dos.
CREATE UNIQUE INDEX uq_categories_user_system ON categories (user_id) WHERE is_system;

CREATE TABLE tags (
    id_tag   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id  bigint      NOT NULL REFERENCES users (id_user) ON DELETE CASCADE,
    name_tag varchar(70) NOT NULL
);

CREATE UNIQUE INDEX uq_tags_user_name ON tags (user_id, lower(name_tag));

CREATE TABLE transactions (
    id_transaction      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount              numeric(12, 2) NOT NULL,
    description         text,
    date                timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_type_id bigint         NOT NULL REFERENCES transaction_types (id_transaction_type),
    user_id             bigint         NOT NULL REFERENCES users (id_user),
    category_id         bigint         NOT NULL REFERENCES categories (id_category),
    CONSTRAINT chk_transactions_amount_positive CHECK (amount > 0)
);

-- Los tres accesos habituales al historial parten siempre del usuario y filtran por fecha,
-- categoria o tipo, de modo que el indice compuesto cubre la consulta sin tocar la tabla.
CREATE INDEX idx_transactions_user_date ON transactions (user_id, date);
CREATE INDEX idx_transactions_user_category ON transactions (user_id, category_id);
CREATE INDEX idx_transactions_user_type ON transactions (user_id, transaction_type_id);

CREATE TABLE transaction_tags (
    id_transaction_tag bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    transaction_id     bigint NOT NULL REFERENCES transactions (id_transaction) ON DELETE CASCADE,
    tag_id             bigint NOT NULL REFERENCES tags (id_tag) ON DELETE CASCADE,
    CONSTRAINT uq_transaction_tags UNIQUE (transaction_id, tag_id)
);

CREATE INDEX idx_transaction_tags_tag ON transaction_tags (tag_id);
